image: henghung/ioex_carrier_base:v1.0.0
stages:
  - build

build_master:
  stage: build
  only:
    - master
  script:
    - mkdir -p /build
    - cd /build && git clone http://$CARRIER_DEPLOY_TOKEN:$CARRIER_DEPLOY_PASSWORD@git.pin2wall.com/P2PNetwork/ioeX.BravoMesh.CarrierModule.git
    - cd /build/ioeX.BravoMesh.CarrierModule && git checkout master
    - cd /build/ioeX.BravoMesh.CarrierModule/build && ./linux_build.sh

build_develop:
  stage: build
  only:
    - develop
  script: 
    - mkdir -p /build
    - cd /build && git clone http://$CARRIER_DEPLOY_TOKEN:$CARRIER_DEPLOY_PASSWORD@git.pin2wall.com/P2PNetwork/ioeX.BravoMesh.CarrierModule.git
    - cd /build/ioeX.BravoMesh.CarrierModule && git checkout develop
    - touch /build/ioeX.BravoMesh.CarrierModule/build/environ/gitlab.mk
    - echo GITLAB_USERNAME = $TOXCORE_DEPLOY_TOKEN >> /build/ioeX.BravoMesh.CarrierModule/build/environ/gitlab.mk
    - echo GITLAB_PASSWORD = $TOXCORE_DEPLOY_PASSWORD >> /build/ioeX.BravoMesh.CarrierModule/build/environ/gitlab.mk
    - cd /build/ioeX.BravoMesh.CarrierModule/build && ./linux_build.sh

build_file_deploy:
  stage: build
  only:
    - file_deploy
  script: 
    - mkdir -p /build
    - cd /build && git clone http://$CARRIER_DEPLOY_TOKEN:$CARRIER_DEPLOY_PASSWORD@git.pin2wall.com/P2PNetwork/ioeX.BravoMesh.CarrierModule.git
    - cd /build/ioeX.BravoMesh.CarrierModule && git checkout file_deploy
    - touch /build/ioeX.BravoMesh.CarrierModule/build/environ/gitlab.mk
    - echo GITLAB_USERNAME = $TOXCORE_DEPLOY_TOKEN >> /build/ioeX.BravoMesh.CarrierModule/build/environ/gitlab.mk
    - echo GITLAB_PASSWORD = $TOXCORE_DEPLOY_PASSWORD >> /build/ioeX.BravoMesh.CarrierModule/build/environ/gitlab.mk
    - cd /build/ioeX.BravoMesh.CarrierModule/build && ./linux_build.sh
